apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.platform.feggah.com
spec:
  claimNames:
    kind: Cluster
    plural: clusters
  connectionSecretKeys:
  - kubeconfig
  group: platform.feggah.com
  names:
    kind: XCluster
    plural: xclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                description: Cluster configuration parameters.
                properties:
                  region:
                    type: string
                    description: Region to which the cluster is created.
                    enum:
                      - us-east
                      - us-central
                  nodes:
                    type: object
                    description: Node configuration parameters.
                    properties:
                      count:
                        type: integer
                        description: Desired node count.
                      tier:
                        type: string
                        description: Tier of node.
                        enum:
                        - small
                        - medium
                        - large
                    required:
                    - count
                    - tier
                  network:
                    type: string
                    description: The network to which the cluster is connected.
                required:
                - nodes
                - network
                - region
            required:
            - parameters
