apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-example
  annotations:
    meta.crossplane.io/maintainer: Gabriel Ferreira <gabidferreira9@gmail.com>
    meta.crossplane.io/source: github.com/Feggah/platform-example
    meta.crossplane.io/description: |
      This example platform is a starting point to teach and exemplify how
      Crossplane works.
spec:
  crossplane:
    version: ">=v1.9.0-0"
  dependsOn:
    - provider: crossplanecontrib/provider-gcp
      version: ">=v0.22.0"
    - provider: crossplanecontrib/provider-azure
      version: ">=v0.20.0"
